language: ruby

branches:
  only:
    - master

rvm:
  - 2.2
  - 2.1
  - ruby-head
  - rbx-2.5.8
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2.5.8
    - rvm: jruby-head

before_install:
  - gem install bundler
